spring.application.name=CDR_Bill
spring.datasource.url=jdbc:mysql://localhost:3306/cdr_bill
spring.datasource.username=root
spring.datasource.password=newpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true